server:
  port: 10086 #设置端口号
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false #把自己注册到eureak服务器列表
    fetch-registry: false #拉取euraka服务信息
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 5000 #每隔五秒，进行一次服务列表的清理
spring:
  application:
    name: leyou-registry #设置name名称